### ISSUE TITLE
migrate to Gatsby Head

### ISSUE THREAD

**Issue by flexbox** [flexbox/artaufeminin#159]
- [x] sunset `react-helmet` and [`gatsby-plugin-react-helmet`](https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet/)
- [ ] [migrate to `gatsby-head`](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/)

## Phase 1

- [ ] 🔥 add SEO component 
```
import SEO from "../components/seo"
```

## Phase 2

Bring back SEO for 

### Pages

- [ ] 404
- [ ] about
- [ ] articles
- [ ] citations
- [ ] faq
- [ ] index
- [ ] links
- [ ] livres
- [ ] podcasts
- [ ] press
- [ ] start

## Templates

- [ ] article
- [ ] book
- [ ] episode

**Comment by flexbox** [comment]
SEO is wrong

![image](https://github.com/flexbox/artaufeminin/assets/360936/477a7bae-9efc-41a1-b655-cad223e2138e)

- `title` 
- `meta`
- ....

should be defined on `head` and not on `main`
