### ISSUE TITLE
SEO checklist

### ISSUE THREAD

**Issue by flexbox** [flexbox/artaufeminin#55]
Some Of Your Error On The Website: artaufeminin.fr

- [x] 4 Pages With Harmful Broken Links
- [x] No Meta Tag & Title Tag
- [x] Your Website Doesn't Have A Canonical Tag.
- [x] Your Website Doesn't Have A Updated Sitemap.
- [x] Google Bot Is Not Able To Crawl Your Website.

**Comment by MatthysDucrocq** [comment]
Fix
